### PR TITLE
Lints existing code base with pre-commit & markdownlint-cli2

### LINKED ISSUE #54: Lint existing code base and update contributing instructions
Further to #46 which was closed by #48 the remaining code base needs linting with the rules that have been introduced. To ensure commits adhere to the rules [pre-commit.ci](https://pre-commit.ci) has requested access to work with this repository so that Pull Requests are checked for compliance with the coding style.

Contributing guidelines should be updated to help guide contributors through installing and configuring [pre-commit](https://pre-commit.com) locally.

Further a `.git-blame-ignore-revs` file should be introduced and commits added so that the blame associated with linting is ignored and changes to the code are attributed to authors rather than those who have linted the code.

### PR DESCRIPTION
**Pull request by ns-rse**
Closes #54

Lints existing code base with basic [pre-commit](https://pre-commit.com) rules and [markdownlint-cli2](https://github.com/DavidAnson/markdownlint-cli2) pre-commit hook.

Aside from `about.md` and `LICENSE.md` most changes are courtesy of the `end-of-file-fixer`.

In addition...

+ Adds ignore rule for svg files to `.markdownlint-cli2.yaml` configuration.
+ Introduces `.git-blame-ignore-revs` file to ignore commits associated with linting (including this one via `git commit -a`). For more on this file see [Who's to Blame?](https://rse.shef.ac.uk/blog/git-blame/).
+ Adds Emacs temporary files to `.gitignore`.

### CODE REVIEW

**Comment by ns-rse** [comment]
Hmm, not sure why the `*.svg` files were linted given the glob rule for includes and the explicit exclusions. :thinking: 

I'll investigate and resolve.

**Comment by davehorsfall** [comment]
@ns-rse, just wanted to acknowledge this PR. Thanks for creating and will review in the next couple of days. I was bogged down last week.

**Comment by ns-rse** [comment]
Thanks @davehorsfall and not a problem at all (I love `pre-commit` and think its a great tool to use). I've similarly been busy but will see if I can work out why the glob/ignores aren't being respected correctly by `markdownlint-cli2` soon.

**Review by davehorsfall — CHANGES_REQUESTED** [review]
Great job. The only outstanding thing is the issue with `*.svg` files still being linted. I've replicated that locally too, despite them being ignored in the config.

**Comment by davehorsfall** [comment]
@ns-rse I also wanted to ask about the **pre-commit ci** plugin that has been activated on the repo. If a contributor commits code that fails the linting checks, what happens? Will it be rejected, or will it just notify and attempt to fix, etc? I just wanted to understand if this presents a technical barrier to people who don't adopt `pre-commit`, but want to contribute. Thanks.

**Comment by ns-rse** [comment]
I'll take a look at the `.svg` issue after work and try and suss it out.

With regards to `pre-commit.ci` and contributions it depends on how the repository is set up and what the errors are.

If `markdownlint-cli2` can correct the errors it will do so and `pre-commit.ci` will automatically make add a commit to the PR so these are incorporated in the pull request.

If they can't be corrected then it depends on how the branch protection rules are configured for `main` and whether the _Require status checks to pass before merging_ option is selected.

Broadly I'd encourage adoption of `pre-commit` since it helps push capturing problems further "left"(/earlier) in the development pipeline/cycle. I realise however not everyone may be willing to do so, in which case there are two options that I can think of...

1. Merge text/code that doesn't pass the linting hooks that are in place.
2. Someone else resolves them on the contributors behalf and adds the commits to the PR.

**Comment by davehorsfall** [comment]
Thanks for clarifying. It's OK for the `pre-commit` setup to mandate that errors are fixed before a PR is merged. This can be managed during the review stage, and allows us to maintain good code quality. 

I was just concerned that contributions from people might be completely rejected if they didn't pass checks, which would significantly decrease the accessibility of the project.

**Comment by ns-rse** [comment]
Ok, I'm a fool and wasn't reading the output carefully enough as has been kindly pointed out to me. Its not `markdownlint-cli2` that is doing the linting here, rather its the `end-of-file-fixer` from the earlier `pre-commit-hooks`. Looking at the affected files the change doesn't appear to have had any impact on their rendering so I guess there is no harm.

**Comment by davehorsfall** [comment]
Its always obvious with hindsight! :smile: 

You're right, the final new line in the svg doesn't impact rendering.

**Review by davehorsfall — APPROVED** [review]

**Pull request merged**
